<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net10.0;net8.0;net6.0</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <!-- NuGet package information -->
    <PackageId>Json.Easy</PackageId>
    <Version>1.0.1</Version>
    <Authors>tifish</Authors>
    <Company></Company>
    <Description>A light wrapper of .NET System.Text.Json for easy usage.</Description>
    <PackageTags>dotnet;json</PackageTags>
    <RepositoryUrl>https://github.com/tifish/Json.Easy</RepositoryUrl>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <!-- Optional but very common -->
    <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
  </PropertyGroup>
  <ItemGroup>
    <None Include="../README.md" Pack="true" PackagePath="/" />
  </ItemGroup>
</Project>
